# Base image
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY dist .
COPY node_modules ./node_modules

# Start the server using the production build
CMD [ "node", "src/main.js" ]