apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rabbitmq
spec:
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
    name: ui
  - port: 5672
    protocol: TCP
    targetPort: 5672
    name: amqp
  - port: 15692
    protocol: TCP
    targetPort: 15692
    name: other
  selector:
    name: rabbitmq-deployment
status:
  loadBalancer: {}
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq-deployment
  template:
    metadata:
      labels:
        name: rabbitmq-deployment
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}
---
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rabbitmq-backup
spec:
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
    name: ui
  - port: 5672
    protocol: TCP
    targetPort: 5672
    name: amqp
  - port: 15692
    protocol: TCP
    targetPort: 15692
    name: other
  selector:
    run: rabbitmq-backup-deployment
status:
  loadBalancer: {}
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: rabbitmq-backup-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq-backup-deployment
  template:
    metadata:
      labels:
        name: rabbitmq-backup-deployment
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}
